### ISSUE TITLE
取得サイト設定

### ISSUE THREAD

**Issue by shosatojp** [uec-world-dominators/watchcat#4]
```yaml
version: '1'
sites:
- title: Google
  url: https://google.com/
  # cmd省略した場合はデフォルトでget method

- title: 1類
  cmd: curl -u z2910999:hogehogehoge $url
  enabled: true
  notify: line1
  env:
    url: https://www.c1.uec.ac.jp/internal/b3/

- title: 計算理論シラバス
  cmd: uecli syllabus get -t 31 -c 21124231
  enabled: true
  env:
    http_proxy: socks5://localhost:1080
    https_proxy: socks5://localhost:1080

- title: ~~~~シラバス
  cmd: uecli --html syllabus get -t 31 -c 21124231
  template: uec_internal

notify:
  slack1:
    isDefault: true
    type: slack-webhook
    webhook: https://hoge.slack.com/hgoehogehogeho/hgoehogehogeho
  line1:
    type: line-notify
    webhook: https://linenotify/
  hoge:
    type: cmd
    cmd: sendmail hogehoge@example.com

template:
  uec_internal:
    env:
      http_proxy: socks5://localhost:1080
      https_proxy: socks5://localhost:1080
```
