### ISSUE TITLE
Basic認証の設定追加

### ISSUE THREAD

**Issue by shosatojp** [uec-world-dominators/watchcat#7]
今のままでcurlコマンドを呼び出すのでも問題ないが、Basic認証はよく使いそうなので設定できるようにする。

```yaml
version: "1"
resources:
  - title: uec
    url: https://www.c1.uec.ac.jp/internal/b3/
    auth:
      basic:
        username: z2020999
        password: hogehogehoge
```

- 以下の2つのクラスを認証用に作る

  ```
  Authenticator <|-- BasicAuthenticator
  ```

- Resourceのコンストラクタで渡す
