### ISSUE TITLE
設定ファイル中で環境変数を使えるようにする

### ISSUE THREAD

**Issue by shosatojp** [uec-world-dominators/watchcat#8]
- パスワードなどの秘密情報を分離する

```yaml
version: "1"
resources:
  - title: uec
    url: https://www.c1.uec.ac.jp/internal/b3/
    auth:
      basic:
        username: ${{UEC_USERNAME}}
        password: ${{UEC_PASSWORD}}
```

- 適当な構文で（上記はGitHub Actionsのもの）
