### ISSUE TITLE
ResourceにIDを必須にする

### ISSUE THREAD

**Issue by shosatojp** [uec-world-dominators/watchcat#9]
- DBに保存することを考えるとほしい
- 代わりに`title`は省略可能に

```yaml
version: "1"
resources:
  google-top-page:
    url: https://google.com/
```
